### ISSUE TITLE
Add a Couchbase backend

### ISSUE THREAD

**Issue by makara** [Wiredcraft/loopback-cache#6]
@CCharlieLi Can you help me add a Couchbase backend. Please use the latest version of our `couchbase3` connector and use the `options` argument to set the timeouts. It doesn't really matter you use which hook to set it, as long as it does the job. Please send me a PR.

**Comment by CCharlieLi** [comment]
Working on it.

**Comment by CCharlieLi** [comment]
There's a problem when try to add  mixin for couchbase with `after save` hook. When use `create` `update` `save` to trigger `after save` hook, it only returns `CouchbaseCas` object instead of document id, and we need that id to use `touch` to set expiration timeout. And for now only the `*find*` methods which trigger `loaded` hook will return a value with document id. Maybe we can add doc id in the return of `Loopback-connector-couchbase3` if there's not one as a convenience.

**Comment by makara** [comment]
Can you try with the "before save" hook and set the "expiry" to the options (one of the saving arguments).

**Comment by CCharlieLi** [comment]
Thanks. Done.
